[[linter]]
code = 'BLACK'
include_patterns = ['**/*.py']
command = [
    'python3',
    'tools/lint/black_linter.py',
    '--',
    '@{{PATHSFILE}}'
]
init_command = [
    'python3',
    'tools/lint/pip_init.py',
    '--dry-run={{DRYRUN}}',
    'black==22.3.0',
]
