repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-toml
      - id: check-yaml
        exclude: packaging/.*
      - id: end-of-file-fixer

  - repo: https://github.com/omnilib/ufmt
    rev: v2.5.1
    hooks:
      - id: ufmt
        additional_dependencies:
          - black == 24.2.0
          - usort == 1.0.8.post1
