# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Push Binary Nightly

on:
  workflow_call:
    secrets:
      AWS_PYTORCH_UPLOADER_ACCESS_KEY_ID:
        required: true
      AWS_PYTORCH_UPLOADER_SECRET_ACCESS_KEY:
        required: true
      PYPI_TOKEN:
        required: false
  # run every day at 11:15am
  schedule:
    - cron:  '15 11 * * *'
  # or manually trigger it
  workflow_dispatch:
  pull_request:

jobs:
  # build on cpu hosts and upload to GHA
  build_on_cpu:
    strategy:
      matrix:
        include:
         - os: linux.2xlarge
           python-version: 3.7
           python-tag: "py37"
           cuda-tag: "cu11"
         - os: linux.2xlarge
           python-version: 3.8
           python-tag: "py38"
           cuda-tag: "cu11"
         - os: linux.2xlarge
           python-version: 3.9
           python-tag: "py39"
           cuda-tag: "cu11"

    uses: /pytorch/test-infra/github/workflows/linux_job.yml
    with:
      runner: ${{ matrix.os }}
      timeout: 60
      upload-artifact: torchrec_nightly_${{ matrix.python-version }}_${{ matrix.cuda-tag }}.whl
      script: |
        ldd --version
        sudo yum update -y
        sudo yum -y install git python3-pip
        sudo pip3 install --upgrade pip
        conda create --name build_binary python=${{ matrix.python-version }}
        conda info
        python --version
        conda run -n build_binary python --version
        sudo yum install -y gcc gcc-c++
        conda install -n build_binary -y pytorch pytorch-cuda=11.7 -c pytorch-nightly -c nvidia
        conda install -n build_binary -y cudnn
        conda run -n build_binary python -m pip install -r requirements.txt
        conda run -n build_binary python -c "import torch.distributed"
        echo "torch.distributed succeeded"
        conda run -n build_binary python -c "import skbuild"
        echo "skbuild succeeded"
        conda run -n build_binary python -c "import numpy"
        echo "numpy succeeded"
        rm -r dist || true
        conda run -n build_binary \
            python setup.py bdist_wheel \
            --package_name torchrec-nightly \
            --python-tag=${{ matrix.python-tag }}

  test_on_gpu:
    env:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
    strategy:
      matrix:
        os: [linux.4xlarge.nvidia.gpu]
        python-version: [3.7, 3.8, 3.9]
        cuda-tag: ["cu11"]
    needs: build_on_cpu
    uses: /pytorch/test-infra/github/workflows/linux_job.yml
    with:
      runner: ${{ matrix.os }}
      timeout: 60
      down-artifact: torchrec_nightly_${{ matrix.python-version }}_${{ matrix.cuda-tag }}.whl
      script: |
        ldd --version
        cat /proc/cpuinfo
        cat /proc/version
        set -euo pipefail
        function get_ec2_metadata() {
          # Pulled from instance metadata endpoint for EC2
          # see https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html
          category=$1
          curl -fsSL "http://169.254.169.254/latest/meta-data/${category}"
        }
        echo "ami-id: $(get_ec2_metadata ami-id)"
        echo "instance-id: $(get_ec2_metadata instance-id)"
        echo "instance-type: $(get_ec2_metadata instance-type)"
        sudo yum install lshw -y
        sudo lshw -C display
        sudo yum update -y
        sudo yum -y install git python3-pip
        sudo pip3 install --upgrade pip
        conda create --name build_binary python=${{ matrix.python-version }}
        conda info
        python --version
        conda run -n build_binary python --version
        sudo yum install -y gcc gcc-c++
        conda install -n build_binary -y pytorch pytorch-cuda=11.7 -c pytorch-nightly -c nvidia
        conda install -n build_binary -y cudnn
        ls -R
        rm -r dist || true
        conda run -n build_binary python -m pip install *.whl
        conda run -n build_binary \
          python -c "import torchrec"
        conda run -n build_binary python -m pip install twine
        conda run -n build_binary \
          python -m twine upload \
            --username __token__ \
            --password "${{ secrets.PYPI_TOKEN }}" \
            --skip-existing \
            torchrec_nightly-*.whl \
            --verbose
