name: pre-commit

on:
  push:
    branches: [main]
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
          packages: |
            ufmt==1.3.0
            black==21.9b0
            usort==0.6.4
      - name: Checkout Torchrec
        uses: actions/checkout@v2
      - name: Run pre-commit
        uses: pre-commit/action@v2.0.3
