name: Pyre

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  pyre:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Torchrec
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - name: Install Dependencies
        run: |
          set -eux
          python -m pip install --upgrade pip
          pip install torch
          VERSION=$(grep "version" .pyre_configuration | sed -n -e 's/.*\(0\.0\.[0-9]*\).*/\1/p')
          pip install pyre-check-nightly==$VERSION
      - name: Run Pyre
        run: |
          scripts/pyre.sh
