# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CPU Unit Test CI

on:
  push:
    paths-ignore:
      - "docs/*"
      - "third_party/*"
      - .gitignore
      - "*.md"
  pull_request:
    paths-ignore:
      - "docs/*"
      - "third_party/*"
      - .gitignore
      - "*.md"

jobs:
  build_test:
    strategy:
        matrix:
          include:
            - os: linux.2xlarge
              python-version: 3.7
              python-tag: "py37"
              cuda-tag: "cpu"
            - os: linux.2xlarge
              python-version: 3.8
              python-tag: "py38"
              cuda-tag: "cpu"
            - os: linux.2xlarge
              python-version: 3.9
              python-tag: "py39"
              cuda-tag: "cpu"
    uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
    with:
      runner: ${{ matrix.os }}
      timeout: 30
      script: |
        ldd --version
        conda create -y --name build_binary python=${{ matrix.python-version }}
        conda info
        python --version
        conda activate build_binary
        python --version
        conda install \
          --yes \
          -c pytorch-nightly \
          "pytorch-nightly"::pytorch[build="*cpu*"]
        pip install -r requirements.txt
        pip uninstall fbgemm_gpu-nightly -y
        pip install fbgemm-gpu-nightly-cpu
        python -c "import torch.distributed"
        echo "torch.distributed succeeded"
        python -c "import skbuild"
        echo "skbuild succeeded"
        python -c "import numpy"
        python -c "import fbgemm_gpu"
        echo "fbgemm_gpu succeeded"
        echo "numpy succeeded"
        python setup.py bdist_wheel \
          --package_name torchrec-test-cpu \
          --python-tag=${{ matrix.python-tag }}
        python -c "import torchrec"
        conda install -y pytest
        python -m pytest torchrec -v -s -W ignore::pytest.PytestCollectionWarning --continue-on-collection-errors -k 'not test_sharding_gloo_cw'
        echo "Starting C++ Tests"
        export CONDA_BACKUP_CXX=$(which gcc)
        echo $CONDA_BACKUP_CXX
        conda install -y gxx_linux-64
        x86_64-conda-linux-gnu-g++ --version
        mkdir cpp-build
        cd cpp-build
        cmake \
            -DBUILD_TEST=ON \
            -DCMAKE_PREFIX_PATH=/opt/conda/envs/build_binary/lib/python${{ matrix.python-version }}/site-packages/torch/share/cmake ..
        make -j
        ctest -v .
