name: Unit Test CI

on:
  push:
    paths-ignore:
      - "docs/*"
      - "third_party/*"
      - .gitignore
      - "*.md"
  pull_request:
    paths-ignore:
      - "docs/*"
      - "third_party/*"
      - .gitignore
      - "*.md"
  workflow_dispatch:

jobs:
  build_on_cpu:
    strategy:
        matrix:
          include:
            - os: linux.2xlarge
              python-version: 3.7
              python-tag: "py37"
              cuda-version: "11.7"
            - os: linux.2xlarge
              python-version: 3.8
              python-tag: "py38"
              cuda-version: "11.7"
            - os: linux.2xlarge
              python-version: 3.9
              python-tag: "py39"
              cuda-version: "11.7"
            - os: linux.2xlarge
              python-version: '3.10'
              python-tag: "py310"
              cuda-version: "11.7"
    uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
    with:
      runner: ${{ matrix.os }}
      timeout: 60
      gpu-arch-type: cuda
      gpu-arch-version: "${{ matrix.cuda-version }}"
      upload-artifact: torchrec-test_${{ matrix.python-version }}_${{ matrix.cuda-version }}.whl
      script: |
        set -x
        ldd --version
        conda create -y --name build_binary python=${{ matrix.python-version }}
        conda info
        conda activate build_binary
        conda install -y pytorch pytorch-cuda=11.7 -c pytorch-nightly -c nvidia
        python -m pip install -r requirements.txt
        python -c "import torch.distributed"
        echo "torch.distributed succeeded"
        python -c "import skbuild"
        echo "skbuild succeeded"
        python -c "import numpy"
        echo "numpy succeeded"
        python setup.py bdist_wheel \
          --package_name torchrec-test \
          --python-tag=${{ matrix.python-tag }} \
          --dist-dir=${RUNNER_ARTIFACT_DIR}
  test_on_gpu:
    needs: build_on_cpu
    strategy:
        matrix:
          os: [linux.4xlarge.nvidia.gpu]
          cuda-tag: ["cu11"]
          python-version: [3.7, 3.8, 3.9, '3.10']
          cuda_version: ["11.7"]
    uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
    with:
      runner: ${{ matrix.os }}
      timeout: 60
      gpu-arch-type: cuda
      gpu-arch-version: "${{ matrix.cuda_version }}"
      download-artifact: torchrec-test_${{ matrix.python-version }}_${{ matrix.cuda-tag }}.whl
      script: |
        set -x
        ldd --version
        conda create -y --name build_binary python=${{ matrix.python-version }}
        conda info
        conda activate build_binary
        conda install -y pytorch pytorch-cuda=11.7 -c pytorch-nightly -c nvidia
        # Install torchrec binary
        conda install "${RUNNER_ARTIFACT_DIR}/*.whl"
        conda install -y pytest
        python -m pytest torchrec -v -s -W ignore::pytest.PytestCollectionWarning --continue-on-collection-errors
