name: GPU Unit Test CI

on:
  push:
    paths-ignore:
      - "docs/*"
      - "third_party/*"
      - .gitignore
      - "*.md"
  pull_request:
    paths-ignore:
      - "docs/*"
      - "third_party/*"
      - .gitignore
      - "*.md"
  workflow_dispatch:

jobs:
  build_on_cpu:
    uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
    with:
      runner: linux.2xlarge
      timeout: 60
      gpu-arch-type: cuda
      gpu-arch-version: "11.7"
      upload-artifact: torchrec-test_3.8_11.7.whl
      script: |
        set -x
        ldd --version
        conda create -y --name build_binary python="3.8"
        conda info
        conda activate build_binary
        conda install -y pytorch pytorch-cuda=11.7 -c pytorch-nightly -c nvidia
        python -m pip install -r requirements.txt
        ls ${RUNNER_ARTIFACT_DIR}
        echo ${RUNNER_ARTIFACT_DIR}
        python setup.py bdist_wheel \
          --package_name torchrec-test \
          --python-tag="py310" \
          --dist-dir=${RUNNER_ARTIFACT_DIR}
  test_on_gpu:
    needs: build_on_cpu
    uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
    with:
      runner: linux.4xlarge.nvidia.gpu
      timeout: 60
      gpu-arch-type: cuda
      gpu-arch-version: "11.7"
      download-artifact: torchrec-test_3.8_11.7.whl
      script: |
        set -x
        ldd --version
        conda create -y --name build_binary python="3.8"
        conda info
        conda activate build_binary
        conda install -y pytorch pytorch-cuda=11.7 -c pytorch-nightly -c nvidia
        # Install torchrec binary
        ls ${RUNNER_ARTIFACT_DIR}
        echo ${RUNNER_ARTIFACT_DIR}
        pip install "${RUNNER_ARTIFACT_DIR}/torchrec-test_3.8_11.7.whl"
        pip install pytest
        python -m pytest torchrec -v -s -W ignore::pytest.PytestCollectionWarning --continue-on-collection-errors
